# Generated by Django 6.1.1 on 2026-09-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_restaurantes/'),
        ),
    ]
