# Generated by Django 6.1.1 on 2026-09-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='link_cardapio',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
