# Generated by Django 6.1.1 on 2026-09-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_restaurante_link_cardapio'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
