# Generated by Django 6.1.1 on 2026-09-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_categoria_restaurante_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Ex: -6.9811', null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Ex: -34.8339', null=True),
        ),
    ]
