# Generated by Django 6.1.1 on 2026-09-20 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0007_restaurante_latitude_restaurante_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='restaurantes/galeria/', verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=100, null=True, verbose_name='Legenda/Prato')),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='restaurantes.restaurante', verbose_name='Restaurante')),
            ],
        ),
    ]
