# Generated by Django 6.1.1 on 2026-09-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0008_fotorestaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='hora_abertura',
            field=models.TimeField(blank=True, help_text='Ex: 18:00', null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='hora_fecho',
            field=models.TimeField(blank=True, help_text='Ex: 23:30', null=True),
        ),
    ]
