# Generated by Django 6.1.1 on 2026-09-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0009_restaurante_hora_abertura_restaurante_hora_fecho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
